# Mostly copied from https://github.com/taiki-e/cargo-hack/blob/main/.github/workflows/release.yml
name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  create-release:
    if: github.repository_owner == 'danielparks'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: danielparks/github-actions/create-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
