# Mostly copied from https://github.com/taiki-e/cargo-hack/blob/main/.github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - v*.*.*

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  create-release:
    if: github.repository_owner == 'danielparks'
    name: Create
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write # To create release
    steps:
      - uses: danielparks/github-actions/create-release@2f6c98c73f0a8130d737500b59a0fddf749b484d # v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
